- name: Install ufw
  apt:
    pkg: ufw
    update_cache: true
- name: Disable UFW
  ufw:
    state:  disabled
    policy: deny

- name: Add rules
  ufw:
    rule: allow
    port: "{{item.num}}"
    proto: "{{item.proto}}"
  with_items: "{{ufw_ports}}"

- name: Enable UFW
  ufw:
    state:  enabled
    policy: deny
...